### PR TITLE
Add runner description and environment

### PR DESCRIPTION
**Pull request by popstas**

### CODE REVIEW

**Comment by gtrafimenkov** [comment]
Hello @popstas 

Thank you for the pull request.

I had to revert commit cc3e442 because it causes an error: `Cannot use two forms of the same flag: description name`

It seems parameters `description` and `name` actually the same.

```
   --name, --description "foo-bar"                              Runner name [$RUNNER_NAME]

$ gitlab-ci-multi-runner --version
Version:      9.5.1
```

**Comment by popstas** [comment]
Yes, you are right, I don't used `--name` before and don't checked before PR.

I want to add some more features:

- molecule tests instead of plain shell
- docker volumes support (for docker in docker)
- use env variables `REGISTRATION_TOKEN`, `CI_SERVER_URL` when no defined in yaml
- replace `include` to `include_tasks` and drop ansible < 2.4 support
- systemd unit setup as [andrewrothstein/ansible-gitlab-ci-multi-runner](https://github.com/andrewrothstein/ansible-gitlab-ci-multi-runner/blob/master/templates/gitlab-runner.service.j2) (maybe you know, how to do it, at this time I starting gitlab-ci-multirunner manually in tmux in Ubuntu 16.04)

Are you agreed with it? I can send PR's for it.

**Comment by popstas** [comment]
About systemd: just reinstalled gitlab-runner, perhaps I has old version without service installation.

**Comment by popstas** [comment]
I decided that support of env variables `REGISTRATION_TOKEN`, `CI_SERVER_URL` is redundantly. What you think about molecule tests and ansible 2.4+ only support?

**Pull request merged**
